title: Zachary Shah
logo: /assets/img/headshot_circle.png
description: Solving problems in signal processing and machine learning to enhance human outcomes
show_downloads: true
theme: jekyll-theme-minimal